import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/pages/Home.module.css'
import { useForm } from "react-hook-form";
import { useState, useEffect, use } from "react";
import axios from "axios";
import SecurityGroups from "../components/SecurityGroups"
import Instances from '../components/Instances';
import UserGroups from '../components/UserGroups';
import Users from '../components/Users';
import Resume from '../components/Resume';
import Controller from '../components/Controller';
import Loading from '../components/Loading';

const DEBUG = false;
const VARIABLES_ENDPOINT = "http://0.0.0.0:8000/api/aws/variables/";



export default function Home() {
  const [page, setPage] = useState<number>(DEBUG ? 3 : 0);
  const [loading, setLoading] = useState<boolean>(false);

  const [json, setJson] = useState<JsonProps>(
    {
      "security_groups": [],
      "user_groups": [],
      "users": [],
      "instances": []
    }
  );
  useEffect(() => {
    async function loadJson() {
      try {
        const response = await axios.get(VARIABLES_ENDPOINT);
        setJson(response.data);
      } catch (error) {
        console.log(error);
      }
    }
    loadJson();
  }, []);


  return (
    <div className={styles.container}>
      <Head>
        <title>My Dash</title>
        <meta name="My AWS dashboard" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}> My AWS dashboard </h1>
        {!loading && (
          <>
            <div className={styles.container}>
              {page === 0 && (<SecurityGroups json={json} setJson={setJson} />)}
              {page === 1 && (<Instances json={json} setJson={setJson} />)}
              {page === 2 && (<UserGroups json={json} setJson={setJson} />)}
              {page === 3 && (<Users json={json} setJson={setJson} />)}
              {page === 4 && (<Resume json={json} setPage={setPage} setLoading={setLoading} />)}
            </div>
            <Controller page={page} setPage={setPage} />

          </>
        )}
        {loading && <Loading />}
      </main >
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div >
  )
}
